### PR TITLE
ThreeJS rendering in Scratch's Canvas

### PR DESCRIPTION
**Pull request by fath11**
image
it allows Three.js scene to be rendered in Scratch's canvas and co-exist with other sprites

since it is drawn on a `drawable`, you should be able to change its layer and hide it like you would with a normal sprite. the only problems i encountered with it is the camera's mouse control but i am not sure how to fix it.

### CODE REVIEW

**Comment by xiaochen004hao** [comment]
我最近也在研究，不过没什么成功（也是我活跃度不高的原因），既然你做了，那就辛苦你了
已经完成了吗？

**Comment by xiaochen004hao** [comment]
但你为什么要把“设置3D显示器状态”积木删掉

**Comment by xiaochen004hao** [comment]
你们都是从哪里学会“Skin”的？。。。

**Comment by xiaochen004hao** [comment]
（直接追上了“simple3d”扩展😆）
（不过在合并之前我要审核一下，审核之前我还有事，你可以先找找bug，扩展参与人员肯定是有你的了）

**Comment by fath11** [comment]
> Where did you learn "skin"?。。。

a guy uses SimpleSkin that is taken from Simple3D that is later made into its own extension here https://github.com/Xeltalliv/extensions/blob/examples/examples/new-skins-and-drawable-layers.js but the version is missing an important bug fix_(irrelevant to RenderTheWorld)_ https://github.com/Xeltalliv/extensions/commit/a9b5ac101b48c4aae7bed81f653ae734edcd0d48

so we are using Simple3D technology right here 😎

**Comment by fath11** [comment]
> Is it already done?

yes, i don't see any bugs besides the camera mouse control not working

**Pull request merged**
